# Packages and modules
## Package is a collection of modules
## Module is a collection of functions
* User defined modules
* Predefined modules
# File and File operations

In [1]:
import builtins
print(dir(builtins))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError

In [2]:
import math as mt
print(dir(mt))


['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [3]:
print(mt.pow(2,3))

8.0


In [4]:
print(mt.pow(3,3))

27.0


In [5]:
print(mt.pow(9,3))

729.0


In [6]:
print(mt.sqrt(9))

3.0


In [7]:
print(mt.tan(45))

1.6197751905438615


In [8]:
# ceil (round figure, largest value)
a=5.6
print(mt.ceil(a))

6


In [9]:
# floor (smallest value)
a=5.6
print(mt.floor(a))

5


In [12]:
a=5
print(mt.factorial(a))

120


In [14]:
import random as rd
print(dir(rd))

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', '_Sequence', '_Set', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_accumulate', '_acos', '_bisect', '_ceil', '_cos', '_e', '_exp', '_inst', '_log', '_os', '_pi', '_random', '_repeat', '_sha512', '_sin', '_sqrt', '_test', '_test_generator', '_urandom', '_warn', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [16]:
print(rd.randint(10,50))

29


In [17]:
print(rd.random())

0.6812367300836802


# User defined modules

In [18]:
pwd()

'C:\\Users\\ESWER\\Desktop\\PYTHON VIEW'

In [24]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 7E43-9A0F

 Directory of C:\Users\ESWER\Desktop\PYTHON VIEW

07-06-2021  13:58    <DIR>          .
07-06-2021  13:58    <DIR>          ..
07-06-2021  13:06    <DIR>          .ipynb_checkpoints
07-06-2021  13:26           156,967 25-5-2021.ipynb
07-06-2021  13:58             8,941 7-6-2021.ipynb
07-06-2021  13:37                 0 module.py
26-05-2021  13:38             2,456 puppy.jpg
03-06-2021  13:06                72 Untitled1.ipynb
               5 File(s)        168,436 bytes
               3 Dir(s)   9,242,951,680 bytes free


In [27]:
import module
print(module.add(5,10))

15


In [31]:
import module as pt
print(pt.add(5,10))
print(pt.sub(50,10))
print(pt.mul(5,20))

15
40
100


In [32]:
import module as pt 
print(pt.add(5,6))

11


# File is a collection of data
## File operations 
## open
### write() w
### read() r
### append() a
### close


In [33]:
f=open('data.txt','w')
kk=f.write("Good Afternoon")
print(kk) # how much data is printed length is displayed
f.close()

14


In [34]:
f2=open("data1.txt","w")
fk2=f2.write("Good Afternoon\n"*100)
f2.close()

In [35]:
fk2=f2.write("Good Afternoon\n"*100)

ValueError: I/O operation on closed file.

In [40]:
fr=open("data.txt","r")
frr=fr.read()
print(frr)
fr.close()

Good Afternoon


In [42]:
fl=open("data.txt",'r')
flr=fl.readlines()
print(flr)
fl.close()

['Good Afternoon']


In [45]:
fa=open("data.txt",'a')
fw=fa.write("\nGood Evening")
fa.close()

In [51]:
# Task
t=open("data.txt","r")
rt=t.read()
c=1
for i in rt:
    if i=="\n":
        c=c+1
print("Number of lines in file: ",c)

Number of lines in file:  2


In [55]:
t=open("data.txt","r")
rt=t.read()
c=1
for i in rt:
    if i.isalpha:
        c=c+1
print("Number of characters in file: ",c)

Number of characters in file:  40


In [2]:
t=open("data.txt","r")
rt=t.read()
c=1
for i in rt:
    if i=="\n":
        c=c+1
print("Number of lines in file: ",c)
print("Number of characters in file: ",len(rt))

Number of lines in file:  2
Number of characters in file:  39


In [4]:
#no. of words in a file
w=open("data.txt","r")
f=w.read()
wt=f.split()
print("number of words in file:",len(wt))

no.of words in file: 5


In [5]:
import random
print(dir(random))

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', '_Sequence', '_Set', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_accumulate', '_acos', '_bisect', '_ceil', '_cos', '_e', '_exp', '_inst', '_log', '_os', '_pi', '_random', '_repeat', '_sha512', '_sin', '_sqrt', '_test', '_test_generator', '_urandom', '_warn', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [6]:
from random import randint

In [7]:
randint(1,100)

47

In [8]:
# 100 Students marks in file
## find pass students
## find fail students
## first class students

In [11]:
from random import randint
def studentsmarks(n,lb,ub):
    f=open("marks.txt","w")
    for i in range(n):
        mt=randint(lb,ub)
        f.write(str(mt)+"\n")
studentsmarks(100,1,100)

In [14]:
# no.of pass students and fail students data
def passfail():
    pas=1
    fail=1
    with open("marks.txt","r") as fn:
        for i in fn:
            if i>="40":
                pas=pas+1
            else:
                fail=fail+1
        print("Number of students passed in a class",pas)
        print("Number of students failed in a class",fail)
passfail()

Number of students passed in a class 69
Number of students failed in a class 33


In [40]:
def distinction():
    dist=1
    with open("marks.txt","r") as fn:
        for i in fn:
            if i>="85":
                dist=dist+1
        print("Number of students distinction in a class",dist)
distinction()

Number of students distinction in a class 14


In [18]:
for i in range(100):
    f=open("data"+str(i)+".txt","w")

In [19]:
# num="8074513566"
# num2="937652468"
# start ^ end $
## do operations

In [20]:
import re
print(dir(re))

['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', 'IGNORECASE', 'L', 'LOCALE', 'M', 'MULTILINE', 'Match', 'Pattern', 'RegexFlag', 'S', 'Scanner', 'T', 'TEMPLATE', 'U', 'UNICODE', 'VERBOSE', 'X', '_MAXCACHE', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_cache', '_compile', '_compile_repl', '_expand', '_locale', '_pickle', '_special_chars_map', '_subx', 'compile', 'copyreg', 'enum', 'error', 'escape', 'findall', 'finditer', 'fullmatch', 'functools', 'match', 'purge', 'search', 'split', 'sre_compile', 'sre_parse', 'sub', 'subn', 'template']


In [23]:
import re
num=input("enter the number: ")
pt="^[6-9]{1}[0-9]{9}$"
if re.match(pt,num):
    print("Given number is valid")
else:
    print("Not valid")

enter the number: 7247418
Not valid


In [26]:
email=input("enter the mail: ")
pt="^[a-z_.0-9]{4,10}[@][a-z]{3,8}[.][a-z]{3,4}$"
if re.match(pt,email):
    print("Given email is valid")
else:
    print("Not valid")

enter the mail: vedha@gmail.com
Given email is valid


In [27]:
print(dir(re))

['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', 'IGNORECASE', 'L', 'LOCALE', 'M', 'MULTILINE', 'Match', 'Pattern', 'RegexFlag', 'S', 'Scanner', 'T', 'TEMPLATE', 'U', 'UNICODE', 'VERBOSE', 'X', '_MAXCACHE', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_cache', '_compile', '_compile_repl', '_expand', '_locale', '_pickle', '_special_chars_map', '_subx', 'compile', 'copyreg', 'enum', 'error', 'escape', 'findall', 'finditer', 'fullmatch', 'functools', 'match', 'purge', 'search', 'split', 'sre_compile', 'sre_parse', 'sub', 'subn', 'template']


In [33]:
name="VedhaSree"
k=re.findall("Sr",name)
print(k)

['Sr']


In [38]:
name="Vignan college"
s=re.search("nan",name)
print(s)

<re.Match object; span=(3, 6), match='nan'>


In [39]:
name="Vignan college"
sp=re.split("nan",name)
print(sp)

['Vig', ' college']


In [2]:
def distinction():
    dist=1
    with open("marks.txt","r") as fn:
        for i in fn:
            if i>="85":
                dist=dist+1
        print("Number of students passed with distinction in class:",dist)
distinction()

Number of students passed with distinction in class: 14


# List Comprehension

In [4]:
h=[1,2,3,4,5,6]
print(type(h))

<class 'list'>


* [out loop condition]
* output or expression
* Main theme is to reduce code complexity

In [5]:
l=[]
for i in range(10):
    l.append(i)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
[ll for ll in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
data=[ll for ll in range(20) if ll%2==0]
print(data)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [10]:
st=[ch for ch in "Good Afternoon"]
print(st)

['G', 'o', 'o', 'd', ' ', 'A', 'f', 't', 'e', 'r', 'n', 'o', 'o', 'n']


In [19]:
clz=["hi","hello","hai","how are you","how many members are joined","how was class","bad","good","avg"]
nl=[]
for i in clz:
    if "h" in i:
        nl.append(i)
print(nl)

['hi', 'hello', 'hai', 'how are you', 'how many members are joined', 'how was class']


In [22]:
[nlist for nlist in clz if "h" in nlist]

['hi',
 'hello',
 'hai',
 'how are you',
 'how many members are joined',
 'how was class']

In [27]:
[l for l in range(10) if l>4]

[5, 6, 7, 8, 9]

In [28]:
[out for out in (1,2,3,4)]

[1, 2, 3, 4]

In [30]:
[out for out in {1,2,3,4,5,6,1,2,3}]

[1, 2, 3, 4, 5, 6]

In [35]:
l=[[1,2,3],[4,5,6],[7,8,9]] 
[out for l1 in l for out in l1] 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# Iterators and generators

In [37]:
clz=("vignan","women's","dvd")
hello=iter(clz)
print(next(hello))
print(next(hello))
print(next(hello))

vignan
women's
dvd


In [40]:
l=[1,2,3,4,5]
l2=iter(l)
print(next(l2))
print(next(l2))
print(next(l2))
print(next(l2))
print(next(l2))

1
2
3
4
5


* generator is a function which returns one value at a time

In [42]:
def gen():
    yield 1
    yield 2
    yield 3
    yield 4
for i in gen():
    print(i)

1
2
3
4


In [43]:
def gen():
    yield 2
    yield 4
    yield 6
    yield 8
for i in gen():
    print(i)

2
4
6
8


# Map
* Map is builtin function its working like iterating

In [46]:
def add(n):
    return n+n
result=list(map(add,range(10)))
print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [2]:
def taskyield():
    n=2
    while True:
        n**=2
        yield n
a=taskyield()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296


* Class is set of methods and set of variables
* Class is blueprint of object

In [3]:
# class classname:
#   set variables
#   set methods


In [4]:
class hell:
    a=10
    b=20
print(hell.a)
print(hell.b)

10
20


In [5]:
class GoodMorning():
    def great():
        print("Good Morning")
print(GoodMorning.great())

Good Morning
None


In [6]:
class Math:
    def add(a,b):
        return a+b
    def mul(a,b):
        return a*b
    def sub(a,b):
        return a-b
obj=Math
print(obj.add(10,20))
print(obj.mul(5,10))
print(obj.sub(100,50))

30
50
50


* Constructors is to initialize to the data mebers of the class when an object of class is created

In [7]:
# default constructors
class good():
    def __init__(n):
        print("hi students")
ob=good()

hi students


In [9]:
class userdef():
    def __hello__(self,name,role):
        print("hello my name is",name,"my role is",role)
ob=userdef()
ob.__hello__("vedha","student")

hello my name is vedha my role is student


In [12]:
class para:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def sub(self):
        return self.a-self.b
ob=para(100,20)
print(ob.sub())

80


# Inheritance
* Single level
* multi level
* filter, reduce, lambda
* numpy

In [9]:
# Single level inheritance
class A():
    def sample():
        print("This is class A function")
class B(A):
    def sample2():
        print("This is class B function")
obj=B
print(obj.sample())
print(obj.sample2())

This is class A function
None
This is class B function
None


In [10]:
class A():
    a=50
    b=20
    def sample():
        print("This is class A function")
class B(A):
    def sample2():
        print("This is class B function")
obj=B
print(obj.a)
print(obj.b)
print(obj.sample())
print(obj.sample2())

50
20
This is class A function
None
This is class B function
None


In [11]:
# Multilevel inheritance
class A():
    a=50
    b=20
    def sample():
        print("This is class A function")
class B(A):
    def sample2():
        print("This is class B function")
class C(B):
    def sample3():
        print("This is class C function")        
obj=C
print(obj.a)
print(obj.b)
print(obj.sample())
print(obj.sample2())
print(obj.sample3())

50
20
This is class A function
None
This is class B function
None
This is class C function
None


In [15]:
def evenodd(n):
    if a%2==0:
        print("even number")
    else:
        print("odd number")
a=int(input("enter a number: "))
evenodd(a)

enter a number: 5
odd number


In [18]:
from oops import Math
obj=Math
print(obj.even(5))
print(obj.odd(3))
print(obj.even(4))
print(obj.odd(6))

False
True
True
False


# filter(fun,iter)

In [26]:
def filterdata(n):
    if n>50 and n%2==0:
        return n
data=filter(filterdata,range(100))
print(list(data))

[52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [25]:
def filterdata(n):
    if n>=50 and n%2==0:
        return n
data=filter(filterdata,range(101))
print(list(data))

[50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [27]:
def filterdata(n):
    if n>50:
        return n
data=filter(filterdata,range(100))
print(list(data))

[51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [28]:
def add(a,b):
    c=a+b
    return c
add(10,90)

100

In [33]:
from functools import reduce
val=[0,1,3,4,5,6]
reduce(add,val)

19

In [34]:
def add(a,b):
    c=a+b
    print("a value is:",a,"b value is:",b,"c value is:",a+b)
    return c
add(10,90)

a value is: 10 b value is: 90 c value is: 100


100

In [35]:
from functools import reduce
val=[0,1,3,4,5,6]
reduce(add,val)

a value is: 0 b value is: 1 c value is: 1
a value is: 1 b value is: 3 c value is: 4
a value is: 4 b value is: 4 c value is: 8
a value is: 8 b value is: 5 c value is: 13
a value is: 13 b value is: 6 c value is: 19


19

In [37]:
# lambda a,b,c:a+b+c
def lamdafun(n):
    return lambda a:a*n
output=lamdafun(2)
print(output(10))

20


In [38]:
def lam(k):
    return lambda a:a*k
out=lam(10)
print(out(2))

20


# Numpy
* It provides a high- performance multi dimentional array object
* more efficiently and with less code
* numpy is python library
* if you want use numpy we can import numpy as np
* num-py Numerical Python
* Scientific calculations
* available onwards 2005

In [39]:
import numpy as np

In [40]:
print(type(np))

<class 'module'>


In [44]:
data=np.array([1,2,3])
print(type(data))

<class 'numpy.ndarray'>


In [46]:
data2=np.array([[1,2,3],[4,5,6]])
print(type(data2))

<class 'numpy.ndarray'>


In [48]:
data2.shape

(2, 3)

In [49]:
data2.ndim

2

In [52]:
data2.nbytes

24

In [56]:
data.dtype

dtype('int32')

In [57]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [60]:
da=np.arange(1,10)
print(da)

[1 2 3 4 5 6 7 8 9]


In [61]:
d2=np.arange(1,100)
print(d2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [67]:
d3=np.arange(0,100,2)
d3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [68]:
d4=np.arange(100,1,-1)
d4

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [69]:
d3[::-1]

array([98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66,
       64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32,
       30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [72]:
d5=np.arange(0,100,2)
d5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [87]:
d5[::-1]

array([98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66,
       64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32,
       30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [88]:
d5[25::-1]

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2,  0])

In [78]:
ze=np.zeros(10)
ze

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
ze=np.ones(10)
ze

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
r=np.arange(12)
k=r.reshape(4,3)
print(k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [91]:
kk=np.full((2,2),9)
kk

array([[9, 9],
       [9, 9]])